### ISSUE TITLE
Have possibility to use just one pane ?

### ISSUE THREAD

**Issue by liberodark** [fman-community/fman#680] opened 2019-08-07 22:00 UTC
Hi,

Have possibility to use one pane and not two all the time ?
Is not good for compress in same folder not on the other pane.
Would be good to add possibility to hide one pane and show two pane.

Best Regards

**Comment by mherrmann** [comment] 2019-08-08 08:53
I'm closing this as a duplicate of #57.

**Comment by mherrmann** [comment] 2019-08-08 08:54
(You can sort of get what you want by dragging the middle divider in fman all the way to the right.)

**Closed as completed by mherrmann** 2019-08-08 08:53 UTC
