### ISSUE TITLE
Windows: single instance option

### ISSUE THREAD

**Issue by krupitskas** [fman-community/fman#736] opened 2020-03-31 14:25 UTC
Hey!
I'm using windows key + 1 / 2 / 3 keys to launch my most useful apps.
Fman bound for 1, as a default file manager, but if I will press windows key + 1 again, it will launch a new instance. You can check the default behavior of sublime text, it will minimize and maximize the window. 
Can we add this option?

**Comment by mherrmann** [comment] 2020-03-31 14:33
Closing this as a duplicate of #81.

**Closed as completed by mherrmann** 2020-03-31 14:33 UTC
