### ISSUE TITLE
Rollback for failed fman updates, ask before updating

### ISSUE THREAD

**Issue by joshas** [fman-community/fman#709] opened 2019-12-05 22:25 UTC
Sometimes new version of fman just doesn't work on some particular system, due to older OS or specific set up. It already has happened twice while using fman for more than a year now.
I was greeted by #707 this morning, had to scramble to find a quick fix. Good thing I found a snapshot of 1.6.7 here https://github.com/fman-users/fman/issues/691#issuecomment-559841093.
I think fman needs a manual update mechanism, where user is informed about new update, its features and in case of disaster, like app not starting at all - quick way to rollback to earlier working version. Or at least provide download links to old versions.
How about providing testing version with rolling auto updates and "stable" one? I understand that packing installers for all platforms with code signing is huge task, but that might help someone like me who is actually using fman for my day job.

**Comment by mherrmann** [comment] 2019-12-06 06:34
I understand your anger, and I'm sorry this happened. Generally, I do try to test new versions. But the real world is more complex than I can replicate on my limited setup, and with my limited time. I do strive to fix critical problems (esp. ones caused by me) as quickly as possible. Regarding #707, I spent all day yesterday looking into this and am hoping to have a solution soon.

Regarding your suggestion, if I were a large organization with many employees then yes, a stable and a "rolling updates" channel could be a solution. But it's just me and the complexity this would introduce is non-negligible.

You can get what you want however: [disable automatic updates](https://fman.io/docs/automatic-updates) and watch the [Changelog](https://fman.io/changelog) for new versions. Then you can decide whether you want to receive a new version, and update manually (by briefly re-enabling automatic updates) if yes.

I'm closing this issue because like I said I do not have the resources to implement a two-channel update mechanism. But like like I said, I understand your frustration, and I'm sorry this happened. It's not fun for me either.

**Closed as completed by mherrmann** 2019-12-06 06:34 UTC

**Comment by joshas** [comment] 2019-12-06 16:39
Sorry if my message sounded a bit angry, but I totally respect the work you do. Your reaction times for solving issues are much faster than some products with hundreds employees. Keep up the good work!
