### ISSUE TITLE
windows OS - fatal error when using Win+arrow shortcut

### ISSUE THREAD

**Issue by citan** [fman-community/fman#522] opened 2018-09-29 23:59 UTC
Dear Michael,

First a big thank you for your tool, it is really an elegant alternative to windows explorer.

I found an issue that systematically happens on windows 10, in the last versions up to the current one:

If you have **2 screens connected to your computer**, with one HDPI and one that is not, if you try to move the fman window from the hdpi screen to the other one using the **keyboard shortcut {WIN key+left or right arrow key}**, windows 10 will crash and show its **blue screen of death**.

**Comment by mherrmann** [comment] 2018-10-01 12:11
Hi Citan,

thank you for the kind words and sorry for the trouble. I'm afraid I cannot reproduce this. Does it happen every time? Does it only happen for fman?

Asking into the general void of the internet: Is anybody else experiencing this too?

Cheers,
Michael

**Comment by citan** [comment] 2018-10-02 00:03
Thank you for your reply.
It happens systematically yes, not only on fman but also on RStudio; I think it is related to the DPI setting of the exectuable. If I have the chance I will do some tests with other dpi settings and from another machine.
Rgds,

**Comment by mherrmann** [comment] 2018-10-02 06:17
I see, thanks for clarifying. If it happens to other applications as well, then I don't think it's a bug in fman, but rather a problem on your machine. (I also searched for similar problem descriptiond for the technologies fman uses and couldn't find anything.) I will close this issue for now. If you do find buggy behaviour that is specific to fman, do feel free to let me know.

**Closed as completed by mherrmann** 2018-10-02 06:17 UTC
Labels: bug, windows
