### ISSUE TITLE
Slow navigation to a directory with ~70k files

### ISSUE THREAD

**Issue by Rush** [fman-community/fman#276] opened 2017-12-28 08:01 UTC
Fman seems way slower than `mc` or `krusader`. When I went to my home dir it took about 3 seconds to open. I have a quad core Core i7 and a fast SSD. My guess is that fman is opening every file in the directory. Scanning the directory should not slow navigation.
```
rush@rushpod: ~ 17ms » pwd
/home/rush
rush@rushpod: ~ » ls -al |wc -c
68910
```

Generally really like the idea of Atom/Sublime like approach to a dual pane file manager. I will observe your project and buy once it's mature enough.

**Comment by mherrmann** [comment] 2017-12-28 08:59
You're right this is an issue. At the moment, I am still adding basic features (such as the recent [support for Zip archives](https://fman.io/blog/zip-support-in-fman/)). Once that's done, I will look into performance. From what I know now, the problem with large numbers of files is actually not the reading from disk, but the rendering. I already have an idea of how to fix it; Just haven't gotten around to it yet.

**Comment by mherrmann** [comment] 2017-12-28 09:37
(May I add your email address to fman's mailing list @Rush? You can unsubscribe at any time and it lets you stay informed about the project. I send out 1 email per month and several people said they really appreciate the updates.)

**Comment by Rush** [comment] 2017-12-28 09:46
Please do.

**Comment by mherrmann** [comment] 2017-12-28 09:48
Done. Thanks.

**Comment by danmou** [comment] 2018-03-08 14:42
It seems like the problem is much worse on my machine. I also have an SSD and i7, but it takes several seconds just to open my Downloads folder, which contains around 100 subdirectories and 700 files. I'm running Linux, in case that explains the difference. In all other file managers I've tried it opens pretty much instantly, so it shouldn't be too hard to achieve better performance.

**Comment by mherrmann** [comment] 2018-03-08 14:43
Yes. It must become faster. I will look into this, just some other issues that are still more pressing first.

**Comment by kszcode** [comment] 2018-03-08 18:23
While we are on this topic, I would like to mention that copy and move is also being run synchronously one by one. So copying even just 100 files in a directory, will result in 100 refresh events, so I can see the files being added one by one.

Normally this should happen on another thread and the refresh should kick in every few seconds.

**Comment by mherrmann** [comment] 2018-03-09 07:57
Hey Kuki,

fman does copy on separate threads. (To be precise, _every_ command runs in a separate thread to keep the UI responsive.) I don't think it's a big problem if files are updated one by one - if they are changed one by one, why not update? Why I think you experience this as bad is simply because the updates are "too slow". That's what I will aim to fix in this issue.

**Comment by jordanholcombe** [comment] 2018-03-29 08:34
still cant open my downloads folder without fman hanging. on windows 10 64 bit machine with fast samsung ssd and i7. normal win10 explorer opens and scrolls through this folder just fine. i'm a developer and after trying a dozens or so file managers over the years, i have to say fman is the clear winner. but this perf problem on large folders has to be fixed. is there something i can do to help?

**Comment by mherrmann** [comment] 2018-03-29 08:35
> is there something i can do to help?

Wait 1-2 weeks. I'm working on fman 1.0.0 that should have 10x better performance ;-)

**Comment by jordanholcombe** [comment] 2018-03-29 08:37
alright i'll survive until then. awesome. thank you :)

**Comment by mherrmann** [comment] 2018-03-29 08:37
:-)

**Comment by zelk** [comment] 2018-04-17 11:02
On my computer, it takes 2 seconds to open my ~/Downloads folder. There are only 490 files in my Downloads folder. Looking forward to 1.0.0. :)

**Comment by mherrmann** [comment] 2018-04-19 10:04
I'm happy to announce that [fman 1.0.0 is out](https://fman.io/blog/fman-10-ten-times-faster/). It's 10x faster than version 0.9.8. Still not as fast as it should be. But a lot better. I would kindly ask everyone who has had trouble with performance to [update](https://fman.io/docs/automatic-updates) and try now.

I will close this issue now, but open a new one to further improve performance.

**Closed as completed by mherrmann** 2018-04-19 10:04 UTC
Labels: enhancement, 7 votes

**Comment by kuzyara** [comment] 2019-01-06 13:39
1.5.3 - %programfiles% still have ~1s lag on my laptop
