### ISSUE TITLE
`Go to` disregards selection when exact path is entered

### ISSUE THREAD

**Issue by rmgk** [fman-community/fman#486] opened 2018-08-21 14:47 UTC
Bit of a follow up on a comment in #485 

If you enter a path in `Go to` say `/home/ragnar` and then use the keyboard or mouse to select one of the entries, e.g., `/home/ragnar/Downloads`:

![bildschirmfoto zu 2018-08-21 16-40-22](https://user-images.githubusercontent.com/151862/44408579-f2938e00-a560-11e8-9c7b-6710dfe3db04.png)

fman will switch to the directory you have entered (i.e., `/home/ragnar`) not the one you selected. Selection does work if the string you entered is not a valid path, i.e., if i en

**Comment by mherrmann** [comment] 2018-08-21 14:51
Oh boy, another one, I'm sorry.

This is another bug caused by my attempted solution for #475. I will fix it by tomorrow because GoTo is very crucial.

**Comment by mherrmann** [comment] 2018-08-22 12:38
Fixed in [fman 1.2.2](https://fman.io/changelog#v1.2.2).

**Closed as completed by mherrmann** 2018-08-22 12:38 UTC
Labels: bug
