### ISSUE TITLE
[Bug] fman 0.7.1: Not able to create/view zip files on macOS 

### ISSUE THREAD

**Issue by raguay** [fman-community/fman#251] opened 2017-12-01 21:59 UTC
I updated all of my plugins for 0.7.*. I just now needed to view what was inside of a zip file. I pressed enter on a zip file created with WinZip and fman showed the path in the directory window with the "zip://" prefix, but the file pane showed nothing. I created a zip with the command line zip program and it wasn't view-able either.

I tried to create a zip file with the "pack" command and this happened:

Command 'Pack' raised error.

Traceback (most recent call last):
  File "fman/impl/plugins/plugin.py", line 270, in _run_in_thread
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/commands.py", line 1373, in __call__
    mkdir(dest_rewritten)
  File "fman/fs.py", line 13, in mkdir
  File "fman/impl/plugins/mother_fs.py", line 68, in mkdir
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/fs/zip.py", line 137, in mkdir
    self._run_7zip(['a', name], cwd=tmp_dir)
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/fs/zip.py", line 271, in _run_7zip
    self._close_7zip(process)
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/fs/zip.py", line 266, in _close_7zip
    raise CalledProcessError(exit_code, process.args)
subprocess.CalledProcessError: Command '['/Applications/fman.app/Contents/Resources/Plugins/Core/bin/mac/7za', 'a', 'synergy.zip']' returned non-zero exit status 127

macOS 10.12.6 (16G1036)
fman 0.7.1

I can't get fman to update to 0.7.2. I've restarted several times and it still will not update. I have this off and on that it will only update every other time.

**Comment by mherrmann** [comment] 2017-12-04 10:17
Hm. What do you get when you run

    /Applications/fman.app/Contents/Resources/Plugins/Core/bin/mac/7za a synergy.zip

in an empty directory?

**Comment by mherrmann** [comment] 2017-12-04 10:18
(Regarding fman not updating, I know it's currently a pain, I'm sorry. You may have to leave fman running for a few minutes before restarting so it has enough time to download the entire update.)

**Comment by mherrmann** [comment] 2017-12-04 10:37
Another user who is experiencing this bug is getting

    $ Applications/fman.app/Contents/Resources/Plugins/Core/bin/mac/7za l /path/to/some.zip
    /Applications/fman.app/Contents/Resources/Plugins/Core/bin/mac/7za: line 2: /usr/local/Cellar/p7zip/16.02/lib/p7zip/7za: No such file or directory

**Comment by raguay** [comment] 2017-12-04 16:57
That is what I get. Are you using Homebrew to install 7za program? I can do it manually, but it doesn't help others. I already have homebrew on my system. If you are trying to install it in fman, the conflict might be stopping the process. Does that other person also have homebrew already installed?

**Comment by raguay** [comment] 2017-12-04 17:02
The updating issue is that fman is running all the time. I only close it when shutting down each night. When I see you have an update on twitter, I restart fman hoping to get it. But it doesn't until there are two updates.

I just installed the 7zip on homebrew and the pack command and viewing that zip file works. But viewing another zip file done with the system "zip" command still doesn't show anything in the file.

**Comment by raguay** [comment] 2017-12-04 17:05
I restated fman and it's able to view the zip file created with the system zip command. I guess fman had the original peek into it cached that didn't show anything. But, if I manually add a file to the zip file, the fman view isn't updated.

**Comment by joshas** [comment] 2017-12-04 18:04
Probably related issue: on macOS opening zip archive displays empty pane, no files. Tested on fman 0.7.3, OS X El Capitan (10.11).

**Comment by mherrmann** [comment] 2017-12-05 06:58
@joshas do you get an error when you use the `Pack` command to create an archive?

**Comment by mherrmann** [comment] 2017-12-05 08:44
I just released version 0.7.4 of fman with an attempt to fix this problem. Can all of you who have been experiencing the issue update (start fman, leave running for a few minutes, then restart it) and let me know if it is resolved?

**Comment by raguay** [comment] 2017-12-05 13:46
It seems to work for me. I'll keep testing it.

**Comment by joshas** [comment] 2017-12-06 17:19
Running `/Applications/fman.app/Contents/Resources/Plugins/Core/bin/mac/7za` I'm getting the same `/usr/local/Cellar/p7zip/16.02/lib/p7zip/7za: No such file or directory` error. I suppose installing 7z using homebrew should fix it, but what about users not using homebrew?
Packing still gives an error on 0.7.4 .

**Comment by kszcode** [comment] 2017-12-06 21:03
Here is a workaround:

For now I fixed it like this:
```
$ which 7za
/usr/local/bin/7za
```

And then I've updated the file: `/Applications/fman.app/Contents/Resources/Plugins/Core/bin/mac/7za` to contain this:

```
$ cat 7za
#! /bin/sh
#"/usr/local/Cellar/p7zip/16.02/lib/p7zip/7za" "$@"
"/usr/local/bin/7za" "$@"
```

**Comment by kszcode** [comment] 2017-12-06 21:06
It might work with a test to see if the 7za file is in a couple of predefined locations, and if not then try to find it like this: `$(which 7za)`

It would not be the most elegant solution, but it would be somewhat better.

**Comment by raguay** [comment] 2017-12-06 23:38
The problem is you are packing a script and not a binary file for 7za. You can see this by

```
more /Applications/fman.app/Contents/Resources/Plugins/Core/bin/mac/7za
#! /bin/sh
"/usr/local/Cellar/p7zip/16.02/lib/p7zip/7za" "$@"```

Replace the script file with the actual binary and your issue is resolved.

**Comment by mherrmann** [comment] 2017-12-07 06:11
Oh my god you are right @raguay! Unbelievable.

**Comment by mherrmann** [comment] 2017-12-07 17:25
As @raguay pointed out, the problem was caused by fman not including the binary file that's required to get the Zip functionality to work on Mac. Instead, fman only contained a skeleton "source file".

I just released version 0.7.5 that adds the actual binary file. Can you all let me know if the Zip functionality on Mac works for you now?

Thank you again for identifying the root cause @raguay.

**Comment by joshas** [comment] 2017-12-08 17:59
I can confirm that fman 0.7.5 on macOS can pack and open zip files without issues.

**Comment by raguay** [comment] 2017-12-08 19:46
Working for me too!

**Comment by mherrmann** [comment] 2017-12-09 15:46
Ok. Finally closing this issue then. Thanks for letting me know.

**Closed as completed by mherrmann** 2017-12-09 15:46 UTC
Labels: bug
