### ISSUE TITLE
the "What You See Is What You Get"  feature seems cracked

### ISSUE THREAD

**Issue by neyangg** [fman-community/fman#487] opened 2018-08-22 06:06 UTC
OS: high sierra 10.13.6
Fman version: v1.1.6 - v1.1.8
Problem Description: when deleted or cut  a file, it seems that the file is still there until refresh (command + R). And system restart wouldn't help. Any advice?

**Comment by mherrmann** [comment] 2018-08-22 08:03
I cannot reproduce this, sorry. How exactly did you delete / cut the file? Here's what I tried (with fman 1.2.1):
 * in fman, move the file to the Trash (<kbd>F8</kbd>)
 * in fman, delete the file permanently
 * while the directory is open in fman, delete the file in Finder

In each case, the file disappeared from fman as expected.

**Comment by neyangg** [comment] 2018-08-27 01:27
Thank you very much for your attention! In my case, except for the last situation, the other two will reproduce the problem all along. And I have no idea how it comes

**Comment by neyangg** [comment] 2018-08-27 01:51
There is one thing to specify, I used to link the configure dir to a net disk, such as

> ln -sf "/Users/neyan/Documents/NetDisk/AppConfig/Fman/User" "/Users/neyan/Library/Application Support/fman/Plugins/User" 

 I wonder if it affects.

**Comment by neyangg** [comment] 2018-08-27 02:09
I reinstalled and the problem repeats, here is my plugin list,

> arrownavigation, favorites, openiterm2, swappanels, unmountvolume, vimnavigation

**Comment by mherrmann** [comment] 2018-08-27 06:17
Is there anything else "unusual" about your system? I mean do you have other apps installed that add files or drives or similar? Does the problem appear in all directories? Eg. does it appear when you delete files from your `Desktop`?

**Comment by neyangg** [comment] 2018-08-28 06:54
Thank you for you reply. I think you are right, there might be something wrong with my system. After running **cleanmymac** , the problem seems disappeared itself!

**Comment by mherrmann** [comment] 2018-08-28 06:54
Cool! Happy to hear it :-) I'll close this issue for now then.

**Closed as completed by mherrmann** 2018-08-28 06:54 UTC
Labels: bug, mac
