### ISSUE TITLE
fman's file timestamps are slow to update

### ISSUE THREAD

**Issue by eostermueller** [fman-community/fman#140] opened 2017-04-10 01:23 UTC
Here, the mac terminal is showing (in the black rectangle) the correct timestamp for a file I'm working on.

![image](https://cloud.githubusercontent.com/assets/175773/24842798/e5823bd6-1d61-11e7-8f4e-9e1df87db2c5.png)

But fman's timestamp does not match:

![image](https://cloud.githubusercontent.com/assets/175773/24842829/37c8ce28-1d62-11e7-803e-400193feb37e.png)

...but when I restarted fman, the timestamp was correct.

**Comment by mherrmann** [comment] 2017-04-10 05:48
I think this is a duplicate of #6.

**Comment by eostermueller** [comment] 2017-04-10 08:26
Yep, agreed.

On Mon, Apr 10, 2017 at 12:48 AM, Michael Herrmann <notifications@github.com

**Comment by mherrmann** [comment] 2017-04-10 08:31
Then if you don't mind I'd like to ask you to vote for the other issue by marking it with a thumbs-up 👍. I'll close this one in the meantime.

**Closed as completed by mherrmann** 2017-04-10 08:31 UTC
Labels: bug

**Comment by eostermueller** [comment] 2017-04-11 02:11
done.
