### ISSUE TITLE
Command "OpenDirectory" raised error

### ISSUE THREAD

**Issue by ekarious** [fman-community/fman#269] opened 2017-12-16 15:41 UTC
Hello, 

I am trying the software and i am currently using the version 0.7.8
I encountered this error when trying to enter a directory by pressing Enter.

I am on macOS High Sierra.
and I removed all plugins i installed.

![screenshot](https://user-images.githubusercontent.com/400070/34071979-91504b0a-e27f-11e7-9d4e-13ceb7cd16d5.png)

**Comment by mherrmann** [comment] 2017-12-19 06:01
Hi,

sorry for the trouble. The only way I could explain this is that perhaps some was still loaded. Does the problem still appear now, after you've presumably restarted fman? If yes, does re-installing fman fix the problem?

Thanks,
Michael

**Comment by raguay** [comment] 2017-12-19 13:51
I've had this issue some. When I reload plugins by command browser fixes the issue. Somewhere there is a version of OpenDirectory that doesn't have the `url` input.

**Comment by raguay** [comment] 2017-12-19 20:40
I've had this issue some. When I reload plugins by command browser fixes the issue. Somewhere there is a version of OpenDirectory that doesn't have the `url` input.

**Comment by mherrmann** [comment] 2017-12-20 08:44
I encountered this with the [VimNavigation](https://github.com/raguay/VimNavigation) plugin, before it was ported to the new file system API. Are you still seeing this issue these days @raguay ?

**Comment by raguay** [comment] 2017-12-20 19:04
Yes. On first loading/running of fman, it calls a different function for going into a directory that doesn't take the url parameter. If I reload plugins, it works fine. There is a load ordering for first start and manually loading the plugins that changes how things work. It happens every time, so it is very reproducible.

**Comment by ekarious** [comment] 2017-12-20 22:30
I do not have the problem anymore. Reinstalling fman fixed it for me.
I'll try to test with installing some plugin later.

Thank you.

PS: I let the issue open if other people still have it.

**Comment by mherrmann** [comment] 2017-12-21 06:48
@raguay so you are seeing the issue every time fman starts?

**Comment by raguay** [comment] 2017-12-21 14:31
Everytime I start fman (ie: not already running) and use the OpenDirectory() command I have tied to `<shift-l>`, it gives this error:
```
Command 'OpenDirectory' raised error.

Traceback (most recent call last):
  File "fman/impl/plugins/plugin.py", line 270, in _run_in_thread
TypeError: __call__() missing 1 required positional argument: 'url'
```
Then when I run the `reload plugins` command from the command prompt and the error goes away. Completely consistent and reproducible. I've looked through the Core for OpenDirectory() command, but the only one I found has the url parameter. 

Now, the definition in Core/commands.py doesn't set the url parameter to None as default. I'm wondering if that is the problem. That would also mean that upon first running fman, Core/commands.py is loaded after the plugins, which would explain why reloading the plugins would fix the issue.

I created the OpenDirectory command in VimNavigation in order to bind it to a key stroke. The original OpenDirectory doesn't work properly when bound to a key stroke and was giving this error. Therefore, this is a two problem area: The OpenDirectory command not working with keystrokes due to not having the required url parameter, and the loading order for plugins on first start is before the Core functions causing function overloading not to work properly.

I guess I could fix VimNavigation to use a different name and that would fix the issue for me on this one account. But, I think the plugin load order needs fixed regardless.

**Comment by mherrmann** [comment] 2017-12-29 15:56
Finally had a little time to look into this. The reason you are getting the error is that the Core plugin's `OpenDirectory` has `__call__(url)` while the `OpenDirectory` from your VimNavigation plugin has `__call__(url=None)`. In general, it is [discouraged](https://fman.io/docs/api#DirectoryPaneListener.on_command) to overwrite commands from another plugin. The problem can be fixed by either

1. removing `OpenDirectory` from `VimNavigation` and changing `{ "keys": ["shift+l"], "command": "open_directory" },` in its `Key Bindings.json` to `{ "keys": ["shift+l"], "command": "open" },` or
2. renaming `OpenDirectory` in `VimNagivation` to something else (eg. `OpenIfDirectory`) and changing `Key Bindings.json` to `{ "keys": ["shift+l"], "command": "open_if_directory" },`

Option 2. has the advantage that `<shift-l>` only opens if the file under the cursor actually is a directory. If it is a file, nothing happens. With option 1., if it were a file, the file would be opened.

I admit I don't know why the error goes away after you've reloaded plugins. But the "official" answer is that overwriting existing commands is not supported. Hope the above helps at least.

**Comment by raguay** [comment] 2017-12-30 15:27
I opted for the 2) option and changed the function name. I also changed it for the "OpenWithEditor" plugin because it was having similar issues. I thought that overriding core commands was accepted. That way, I didn't have to change all the key bindings that call for an editor or opening the directory.

**Closed as completed by raguay** 2017-12-30 15:27 UTC
Labels: bug

**Comment by mherrmann** [comment] 2017-12-31 07:17
Yes, sorry. I had not anticipated that people would like to overwrite commands. I think it's better not to do or encourage it for a few reasons;

1. A user might like to have your plugin's command _and_ the original command, bound to different shortcuts. That's not possible if the plugin command overwrites the original one.
2. The order in which plugins are loaded is [well-defined in theory](https://fman.io/docs/plugins-architecture#plugin-order). But if there are several plugins all overwriting the same command it becomes difficult to keep track of which one will win.
