### ISSUE TITLE
Quick look does not work for some file types

### ISSUE THREAD

**Issue by hpehl** [fman-community/fman#166] opened 2017-05-30 08:21 UTC
For some file types quick look opens the process "qlmanage" and stays in the background. Other file types work somehow, but use the title "[DEBUG]" and miss the buttons you normally see when using quick look from the finder. 

The file types which do not work seem to be those which use custom plugins like [qlmarkdown](https://github.com/toland/qlmarkdown).

Quick look should work the same way as in the finder: 
- No visible process in the dock
- No "[DEBUG]" title
- Buttons to open in associated app

Here's my environment:
- fman version: 0.4.7
- macOS Sierra 10.12.5 (16F73)

**Comment by mherrmann** [comment] 2017-05-30 08:27
Hi Harald, do I understand correctly that this pertains to the [QuickLook plugin](https://github.com/mherrmann/QuickLook)?

**Comment by hpehl** [comment] 2017-05-30 08:33
Yes that's right. And I've assigned a custom key binding "F3" (if that helps).

**Comment by hpehl** [comment] 2017-05-30 09:15
My quick look plugins seem to be messed up. If I run `qlmanage -p` from the command line there are errors and I see the same behaviour. Try to sort this out...

**Comment by hpehl** [comment] 2017-05-30 09:59
This is indeed related to my quicklook plugins. If I uninstall my plugins, it works as expected. Feel free to close this issue.

**Comment by mherrmann** [comment] 2017-05-30 10:03
Interesting! Thank you for letting me know. Closing this issue.

**Closed as completed by mherrmann** 2017-05-30 10:03 UTC
Labels: bug, mac

**Comment by matangover** [comment] 2018-11-27 06:06
@mherrmann I'm experiencing the same problem. Could you please re-open this issue?

I get the issue with Markdown files using qlmarkdown, like @hpehl.
I also get the issue with standard HTML files.

It seems to be a bug in `qlmanage`. On my machine, running:
```
touch hi.html
qlmanage -p hi.html
```
... hangs for a few seconds and then crashes with segmentation fault:
![image](https://user-images.githubusercontent.com/5028956/49061272-5079e680-f1de-11e8-8e13-388abf5dbb65.png)

Running `qlmanage` with `-d 4` confirms that it's using the pre-installed `Web.qlgenerator` from Apple.
Using Finder to QuickLook the same HTML file does work as intended.

Seems like the only solution is to ditch `qlmanage` and use `QLPreviewPanel`. It will make fman QuickLook on par with Finder QuickLook:
- Works for all file types (HTML, Markdown...)
- No visible process in the dock
- No "[DEBUG]" title
- Button to open in associated app
- Share button
- Animation when opening/closing QuickLook
- Autoplay of videos: #450 
- Full screen button

I have anecdotally tested another app which uses QLPreviewPanel - GrandPerspective - and all the above features are available there.

**Comment by raguay** [comment] 2018-11-27 07:12
Hey, Install the "Preview" plugin and configure a program that uses the
QLPreviewPanel OS call yourself. It's a lot easier than waiting for a
software change. It's unlikely to support it since that is an internal OS
command that isn't a part of or used by the Qt Library or Python. fman is
built on the Python/Qt stack and therefore limited by that stack. It is
possible to extend Python or maybe include a library that does (I did find
an example here:
https://programtalk.com/vs2/python/394/music-player/mac/pyobjc-framework-Quartz/PyObjCTest/test_qlpreviewpanel.py/).
But, that would take a little while and a lot of testing.

**Comment by mherrmann** [comment] 2018-11-28 15:54
@matangover I created a new issue for this: #586.
