### ISSUE TITLE
Pull up current instance of fman instead of opening a new one

### ISSUE THREAD

**Issue by omisys** [fman-community/fman#554] opened 2018-10-22 08:18 UTC
When setting a keybind to pull up fman via the shortcut in Windows, fman keeps opening a new instance instead of pulling up the current one. It would be nice to just activate the current instance instead of opening op new instances all the time.

**Comment by mherrmann** [comment] 2018-10-22 12:52
Closing this as a duplicate of #81.

**Closed as completed by mherrmann** 2018-10-22 12:52 UTC

**Comment by keith-hall** [comment] 2018-10-22 12:56
related:
- https://github.com/fman-users/fman/issues/81
- https://github.com/fman-users/fman/issues/462
- https://github.com/fman-users/fman/issues/121
