### ISSUE TITLE
Moving folders stops during the move

### ISSUE THREAD

**Issue by thomas-haslwanter** [fman-community/fman#672] opened 2019-07-19 13:50 UTC
When moving a whole folder, fman stops during the move. Repeated "select and move" necessary to get the whole folder moved.

This issue occurred on Windows 10, 64 bit. Particularly noted during moving large folders.

**Comment by alphaniner** [comment] 2019-07-19 15:44
Duplicated on Win 7 64 bit. Looks like it's related to depth.
I created a directory containing just sub-directories and empty text files. Tree view:
```
0
├── 0.txt
├── 1a
│   └── 1a.txt
├── 1b
│   ├── 1b.txt
│   └── 2b
│       └── 2b.txt
└── 1c
    ├── 1c.txt
    └── 2c
        ├── 2c.txt
        └── 3c
            └── 3c.txt
```
-----
Destination after first move:
```
0
├── 0.txt
├── 1a
├── 1b
└── 1c
```
If you consider the source directory as one level of depth, that's two levels moved.

-----
Destination after second move:
```
0
├── 0.txt
├── 1a
│   └── 1a.txt
├── 1b
│   ├── 1b.txt
│   └── 2b
│       └── 2b.txt
└── 1c
    ├── 1c.txt
    └── 2c
        ├── 2c.txt
        └── 3c
```
That's two more levels moved.

-----
With only one level left, the third move gets it done.

**Comment by mherrmann** [comment] 2019-07-23 13:02
Sorry, I can't reproduce this. I tried moving both `0/` as well as selecting all contents of `0/` (`0.txt`, `1a/`, ...) and moving them. In each case, everything was moved correctly.

Maybe you were moving across volumes @alphaniner? I.e. from a local disk to a RAM disk or a network share?

**Comment by alphaniner** [comment] 2019-07-23 13:59
I have the problem when moving from a local disk to a ramdisk and when moving from one local disk to a different local disk.

No problem when moving to a different location on the same local disk.

**Comment by mherrmann** [comment] 2019-07-25 12:56
Thank you for the excellent research. This is fixed now in [fman 1.6.5](https://fman.io/changelog#v1.6.5).

**Closed as completed by mherrmann** 2019-07-25 12:56 UTC
Labels: bug

**Comment by thomas-haslwanter** [comment] 2019-07-26 07:14
Thank you for the quick fix of that problem!
Also, I have been playing with other file-managers (xyplore). And I have to say - also by comparison: fman is really well done - Thank you!

**Comment by mherrmann** [comment] 2019-07-26 07:26
Thank you for the kind words. Bugs affecting file operations have the highest importance for me so I do try to get to them as quickly as possible.
