### ISSUE TITLE
Not printable characters when copying text to PhpStorm

### ISSUE THREAD

**Issue by joshas** [fman-community/fman#435] opened 2018-07-02 20:00 UTC
Text copied from input dialog (e.g. pressing rename on file and copying filename) on macOS Mavericks and pasted into PhpStorm (from version 2017.3.6 to 2018.1.6) there is a special symbol prepended: U+FEFF &#65279; \uFEFF  (BOM).
It causes many issues, especially when copied to code, as it is invisible and code checking not always catch it.
Haven't tested, but same issue might be with other IDEA products, e.g. PyCharm, etc.
Not really sure, when it started, but it was quite some time ago, I just haven't had time to report it.

**Comment by mherrmann** [comment] 2018-07-16 14:09
This seems to be caused by [QTBUG-61562](https://bugreports.qt.io/browse/QTBUG-61562).

**Comment by mherrmann** [comment] 2018-07-17 06:09
Fixed. Will go live with fman 1.1.4.

**Comment by mherrmann** [comment] 2018-07-17 15:46
Fixed in [fman 1.1.4](https://fman.io/changelog#v1.1.4).

**Closed as completed by mherrmann** 2018-07-17 15:46 UTC
Labels: bug, mac
