### ISSUE TITLE
Light Mode

### ISSUE THREAD

**Issue by mollyhooperwastaken** [fman-community/fman#839] opened 2021-10-25 15:54 UTC
It'd be really nice if there was a light mode version of fman, as (contrary to popular belief) eye strain is not vaused by light mode itself but by a contrast in lighting situations (light mode at night, or in fman's case, dark mode in daytime when all my other programs are light themed).

**Comment by mherrmann** [comment] 2021-10-26 04:59
I think this is a duplicate of #45, so I'm closing it.

**Closed as completed by mherrmann** 2021-10-26 04:59 UTC
