### ISSUE TITLE
"Moving" a folder only copies the (empty) folder name

### ISSUE THREAD

**Issue by thomas-haslwanter** [fman-community/fman#661] opened 2019-06-03 16:18 UTC
When a folder is selected and the "F6" is pushed (for moving), a name with that folder is created in the other pane. But when the old (original) pane is refreshed (CTRL+R), the files in that folder are still there and have not been moved. On second try, it often works.

**Comment by mherrmann** [comment] 2019-06-04 06:18
Sorry, I cannot reproduce this. Could it be that you don't have enough permissions to create files in the destination?

**Comment by karstengresch** [comment] 2019-06-22 12:33
I can reproduce it under Windows. The problem only seems to exist for lager file structures (several nested directories w/ 100s of files).

In my case, the directory structure of the source directory remained but with no files whereas the target directory structure was completely empty, so I had to run a backup (fortunately I had one and only lost a few hours of work).

NB - this only occurs on my PC when moving to a **different drive**. When copying to another directory on the same drive, everything works as expected.

I can reproduce this behavior. When I perform the same action with the native file system manager (i.e. W$ Explorer), the problem does _not_ exist, so it's definitely not a permission problem.

Could you please test with larger directories and different drives under windows?

**Comment by mherrmann** [comment] 2019-06-25 11:33
Very sorry for the trouble @karstengresch. I think I can reproduce this now. (The crucial part is the different drives.) However, while the files in the source pane do disappear, they're not actually deleted. A refresh (<kbd>Ctrl</kbd>+<kbd>R</kbd>) brings them back. I'm looking into this...

**Comment by mherrmann** [comment] 2019-06-25 13:31
Fixed in [fman 1.6.3](https://fman.io/changelog#v1.6.3). Sorry again for the trouble.

**Closed as completed by mherrmann** 2019-06-25 13:31 UTC
Labels: bug, 1 vote
