### ISSUE TITLE
Allow forward slashes in GoTo on Windows

### ISSUE THREAD

**Issue by ababak** [fman-community/fman#308] opened 2018-02-07 10:50 UTC
As a Python user in a cross-platform environment, I use forward slashes in all of my scripts. Please allow forward slashes in Ctrl-P.
Also please consider switching to forward slashes in various parts of fman as a configurable option.
Thanks.

**Comment by mherrmann** [comment] 2018-02-08 18:10
"Forward slashes in GoTo" is a duplicate of #175. If I could kindly ask, please

1. search for existing issues before opening a new one.
2. Only request one thing per issue. In the above example, the "Also..." part would be a separate issue imho.

Speaking of the second part, which other parts of fman do you mean?

**Comment by ababak** [comment] 2018-02-09 09:31
Hi Michael,

Unfortunately, searching for 'slash' showed only #212 which is just the opposite of #308 and searching for '/' and '\' is not supported, I believe. By other parts, I mean at least to copy the path of the selection.

Thanks.

**Comment by mherrmann** [comment] 2018-02-12 06:44
Okay, thank you for the clarification. I'll close this issue and open a new one for the other parts you mentioned (#315).

**Closed as completed by mherrmann** 2018-02-12 06:44 UTC
Labels: enhancement
