### ISSUE TITLE
Show some kind of progress when copying large folders/files

### ISSUE THREAD

**Issue by borzale** [fman-community/fman#131] opened 2017-03-31 00:16 UTC
Currently it only shows "Copying -folder name-" in the bottom status bar while copying large folders. Today I had a 16gig folder to copy into another directory which was frustrating due to not knowing when it would be finished. It also failed to copy for some reason, which is probably another issue I can raise if you need?

It would be great to get some kind of indicator on progress. Don't necessarily have to have estimated time left as a progress indicator is enough information to go off in most cases. Although that would of course be nice!

**Comment by mherrmann** [comment] 2017-03-31 07:00
I think this is already captured by #46. Regarding the copy failing: I would create a separate issue for this. What exactly happened? Did you get an error message?

**Comment by mherrmann** [comment] 2017-05-04 05:48
Closing this as a duplicate of #46 for now.

**Closed as completed by mherrmann** 2017-05-04 05:48 UTC
Labels: enhancement
