### ISSUE TITLE
Make fman default in Windows

### ISSUE THREAD

**Issue by wlgrd** [fman-community/fman#665] opened 2019-06-25 12:47 UTC
I would like to be able to launch fman upon pressing Win+E, since I'm so used to starting my explorer like that.

**Comment by mherrmann** [comment] 2019-06-25 13:13
Closing this as a duplicate of #270. Although if you only want fman to open when you press Win+E, there may be other solutions that let you simply remap that shortcut. Either way, I feel that the correct place for this discussion is #270.

**Closed as completed by mherrmann** 2019-06-25 13:13 UTC
Labels: windows
