### ISSUE TITLE
The `is_dir()` API function is erroring on a non-existing path.

### ISSUE THREAD

**Issue by raguay** [fman-community/fman#526] opened 2018-10-01 15:11 UTC
This was found in an issue for the MoveToDir plugin. The user was trying to move to a new directory. I wrote the program assuming that `is_dir()` would give a false if the directory did not exist and therefore create it. On my system, it is working that way, but the user is finding it not to work.

The issue filed is here: https://github.com/raguay/MoveToDir/issues/2

I forgot to ask what OS. I'll ask him that as well.

**Comment by mherrmann** [comment] 2018-10-01 15:15
This is by design. Quoting from the [API docs](https://fman.io/docs/api#is_dir):

> If the URL does not exist, `FileNotFoundError` is raised. 

So, to check if a URL is an _existing_ directory, you would do:

    try:
        exists_and_is_dir = is_dir(url)
    except FileNotFoundError:
        exists_and_is_dir = False

**Comment by raguay** [comment] 2018-10-01 15:24
Great. I miss understood the intents of the API. So, why does it work on my
system? I've used it this way for quite a while to create new directories
if they don't exist. I'll change the plugin. Thanks.

**Comment by mherrmann** [comment] 2018-10-01 15:31
> So, why does it work on my system?

I'm not sure. Maybe the user simply uses the plugin somehow differently from you(?)

I'll close this issue for now :-)

**Closed as completed by mherrmann** 2018-10-01 15:31 UTC
Labels: discussion

**Comment by raguay** [comment] 2018-10-01 15:36
Okay, where do I import the FileNotFound error. It's not in OS, for fman.fs. Where is it?

**Comment by raguay** [comment] 2018-10-01 15:41
Actually, I fixed it by catching all Exceptions.

**Comment by mherrmann** [comment] 2018-10-01 15:45
It's a default Python exception. You do not need to import it. :-)

**Comment by mherrmann** [comment] 2018-10-01 15:46
(I'd recommend not catching all Exceptions as it may hide errors you are interested in. A simple `except FileNotFoundError` should be enough.)

**Comment by raguay** [comment] 2018-10-02 00:52
It will not load into fman that way. It says the FileNotFoundError can't be
found when loading the plugin. That is why I was asking as to where it is.

**Comment by mherrmann** [comment] 2018-10-02 06:31
There must be some other reason for that. FileNotFoundError definitely does not need to be imported. Do you have the correct case? Eg. FileNotFoundError not FileNotfoundError. Or perhaps you are trying to import it somewhere? Eg. `from ... import FileNotFoundError`.
