### ISSUE TITLE
GoTo on Windows not displaying vertical scroll bars

### ISSUE THREAD

**Issue by Kiedro** [fman-community/fman#324] opened 2018-02-19 19:35 UTC
Long paths are not fully displayed in the GoTo popup, making it impossible to navigate between heavy nested directories with a common root.

Possibility to display full path on the selection of entry,  or multi-line display of paths would be great.

An alternative solution is to replace middle part of the path with '...' (or anything else) so beginning and ending are visible - the most interesting parts in most cases.

**Comment by mherrmann** [comment] 2018-02-20 08:42
Hi, thank you for the suggestion. What do you mean by "possibility to display full path"? At the moment, there is a horizontal scrollbar that should let you see the entire path. Doesn't it?

**Comment by Kiedro** [comment] 2018-02-21 23:05
Hi, I have only vertical scrollbar, as can be seen in the attached screenshot or I don't know how to activate the horizontal one ;). Windows 10.

![image](https://user-images.githubusercontent.com/6191914/36510672-240b163c-1764-11e8-9945-f3c84b74593b.png)

**Comment by mherrmann** [comment] 2018-02-22 07:20
😀 I love your example. And you're right. The scrollbar appears on Mac and Linux, but not on Windows. I'll update this issue to reflect this.

**Comment by IgorKrupenja** [comment] 2018-04-20 09:53
Was this fixed in 1.0.0? I cannot reproduce this with fman v1.0.0 on Windows 10 Home x64 (build 16299.371):

![image](https://user-images.githubusercontent.com/26354715/39044512-0457933a-4499-11e8-9ded-938f345190d1.png)

Horizontal scrollbar is there and scrolling works by dragging the slider, pressing scrollbar arrow buttons and using horizontal scroll wheel on my Logitech MX Master :)

**Comment by mherrmann** [comment] 2018-04-20 10:13
I also cannot reproduce this now, though I did not consciously fix it.

Does the problem still appear for you @Kiedro?

**Comment by Kiedro** [comment] 2018-04-22 20:20
Hi and no, on v1.0.1 both scrollbars are visible. The horizontal scrollbar lacks navigation by left/right arrow keys but besides this everything works as expected.

**Comment by mherrmann** [comment] 2018-04-23 04:40
@Kiedro okay, thank you for letting me know. I'm closing this issue then for now.

**Closed as completed by mherrmann** 2018-04-23 04:40 UTC
Labels: bug, windows, 2 votes
