### ISSUE TITLE
fman 1.6.8 doesn't launch on Mac, see console logs below

### ISSUE THREAD

**Issue by genecivillico** [fman-community/fman#708] opened 2019-12-05 20:46 UTC
default	15:45:09.851669 -0500	loginwindow	-[PersistentAppsSupport applicationReady:] | App: fman, ready, updating active tracking timer
default	15:45:09.851737 -0500	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : fman
default	15:45:09.918833 -0500	kernel	CODE SIGNING: 5543[fman] vm_map_enter: curprot cannot be write+execute. failing
default	15:45:09.951943 -0500	loginwindow	-[PersistentAppsSupport applicationQuit:] | for app:fman, _appTrackingState = 2
default	15:45:09.951976 -0500	loginwindow	-[PersistentAppsSupport applicationQuit:] | App: fman, quit, updating active tracking timer

**Comment by mherrmann** [comment] 2019-12-06 06:28
I suspect this is a duplicate of #707. Sorry for the trouble. I'm working on a solution.

**Closed as completed by mherrmann** 2019-12-06 06:28 UTC
