### ISSUE TITLE
fman deleted my files

### ISSUE THREAD

**Issue by rowadhub** [fman-community/fman#746] opened 2020-04-29 20:18 UTC
I chose several folders, around 10, containing around 500 pictures, from the left pane, F6 to the right panne; folder "hz_done".
The move is done.
I went up a folder on the right pane created a new folder "hz_maybe", enter on the new folder, then went back (I use Backspace) to go back.
"hz_done" is not there.
GoTo "hz_done" it is there, went there, go Backspace, the folder still not there, use GoTo, it doesn't exist.
Searched everywhere, used Everything and Lookeen, nothing.
Thank God these files on Dropbox I can rewind from there.

I think this a serious bug in a file manager.

**Comment by mherrmann** [comment] 2020-04-29 20:38
Sorry about this. Is there a way in which you can reproduce this bug?

**Comment by rowadhub** [comment] 2020-04-30 01:10
https://www.dropbox.com/s/omlwqhkyx4w1obj/fman_recreating_bug.mp4?dl=1

Please see the linked video where I try to reproduce the bug. I didn't succeed but another issue raised which I think is related.

For now, just watch the first 01:30 minutes:

- The warning on 01:02 didn't happen before. But note that because the folder "Delconte" was not moved.

- But the most important thing here is what happens at 01:28; when suddenly all these folders appear in the folder "hz_maybe".
 The folder "hz_maybe" was empty, and it is when I created this folder the first time the files from"hz_done" (when the bug happen) disappeared. But now, from nowhere it is showing the folders that were supposed to be 'hz_done" (when the bug happen). Note these are not the ones I moved to "hz_Done" (capital D, from this recording); as this has the Delconte folder.

For things to disappear and reappear this quick; when it disappeared there was no activity on my desk reflecting the usual deleting, it has something to do with File Table Allocation or what I think what is called inode. So the files are there but something happens in the Table of Content.

For the rest of the video, I am moving more files and trying to recreate a similar situation but didn't work.

**Comment by mherrmann** [comment] 2020-05-01 10:49
I watched up to ~1:30 like you suggested. The error at 1:02 is ugly, I agree. My suspicion is that it was caused by Dropbox trying to in some way sync the file at the same time that fman was accessing it. The fact that hz_maybe was empty and then files appeared in it has (I think) a different explanation: I suspect the folder was not actually empty, but rather that fman simply didn't yet see the files in it. Then, a "reload" happened when you entered the folder, and so the files appeared. In other words, I suspect the files in hz_maybe were there all along, and were only shown in fman after that delay when entering the folder. You can force-refresh in fman by pressing <kbd>Ctrl</kbd>+<kbd>R</kbd>.

None of the above is pretty, or nice. But it does not seem to me like fman is deleting your files. (That would be something I would, and always have, treated with the highest priority.) Unless you find a way that can be used to reproduce a buggy behavior every time, I'm afraid there is not much I can do with reasonable effort.

**Comment by rowadhub** [comment] 2020-05-01 21:51
I went through Dropbox folder activity (Sorry I didn't know that I could do this before) and I found this:
"You renamed hz_done to hz_maybe"

So it seems rather than creating a new folder I renamed the folder.

However, I did look for these folders everywhere using search software, and I do remember I opened hz_maybe several times.

Maybe I am mistaken.

**Comment by mherrmann** [comment] 2020-05-04 05:19
I see. Then I'll close this issue for now until we find a way to reliably reproduce it.

**Closed as completed by mherrmann** 2020-05-04 05:19 UTC
