### ISSUE TITLE
Drag and drop 'move' does not work on Windows

### ISSUE THREAD

**Issue by blokeley** [fman-community/fman#497] opened 2018-08-30 12:15 UTC
I tried dragging a small text file from my Windows 10 desktop into a folder on fman.

Whilst doing this, I held the Shift key to change 'Copy' to 'Move'.

On releasing the file, I got an error dialog in fman saying 'The file could not be found', and the original file had disappeared from my desktop!

I found the original file in the Recycle Bin.

I tried again but this time used 'Copy' rather than holding Shift to use 'Move' and the file copied across.  Strangely, again the original file disappeared from my desktop!

I'm afraid that these sorts of unexpected behaviours are making fman very difficult to use.

Version: fman 1.2.8

**Comment by mherrmann** [comment] 2018-08-30 12:20
My first suspicion is that this was not caused by a bug in fman. When you drop a file on fman, it shows a dialog asking you to confirm the Copy/Move operation. Unless you accept, fman does not copy/move any files.

Are you able to reproduce this all the time with fman? Does it occur when you drag the file into Explorer instead of fman?

**Comment by blokeley** [comment] 2018-09-06 10:19
**Without pressing the `Shift` key whilst dragging the file...**

If I drag a file from my Desktop to fman, the hovering tooltip says `+Copy` but when I release the touchpad, fman creates a dialog box saying `Move "example.txt" to ...`  .  There are 2 problems so far:

1. Surely the hovering tooltip should have said `Move...` rather than `Copy...`
2. If I hit `Enter`, the file opens and the fman dialog box does nothing.

If I click on the fman dialog `OK` button, fman moves the file correctly.

**With pressing the `Shift` key whilst dragging the file...**

The hovering tooltip says `+Move` whilst dragging, and on release an fman dialog box appears saying, `Move "example.txt" to...`.  The problems I get are:

1. Pressing `Enter` does not select `OK` on the dialog box and do the move - nothing happens at all, not even opening the file which happened when I didn't press the `Shift` key (above).

2. If I hit `OK`, I get an fman error dialog saying, "Error moving example.txt (the system cannot find the file specified)".  **The file has been moved to the Recycle Bin which is bad behaviour** - this was the original bug report. 

3. If I cancel the dialog box, the file disappears - it is not in the source or destination folders!  I found it in the Recycle Bin.  This is **really bad behaviour** for a file manager.

So it seems that dragging and dropping from the Desktop has several quite bad bugs.

**Comment by mherrmann** [comment] 2018-09-06 14:44
I can reproduce everything but the focus issues. Thank you for clarifying. You're right this is a pretty bad bug. I'm looking into it...

**Comment by mherrmann** [comment] 2018-09-07 12:52
Fixed in [fman 1.3.0](https://fman.io/changelog#v1.3.0).

**Comment by mherrmann** [comment] 2018-09-07 12:52
(Except for the focus issues I should say.)

**Closed as completed by mherrmann** 2018-09-07 12:52 UTC
Labels: bug
