### ISSUE TITLE
WSL not opening

### ISSUE THREAD

**Issue by deep42** [fman-community/fman#845] opened 2022-02-14 08:08 UTC
Hi, I am having the exact same problem as described in ticket #721 (https://github.com/fman-users/fman/issues/721).
However, the potential solution mentioned there (via stackoverflow) is beyond my level. Could someone please guide me? Thank you

**Comment by mherrmann** [comment] 2022-02-14 08:21
Closing this as a duplicate of #721. Please continue the discussion there.

**Closed as completed by mherrmann** 2022-02-14 08:21 UTC
