### ISSUE TITLE
Optionally remember sorting mode for opened directories

### ISSUE THREAD

**Issue by tmssngr** [fman-community/fman#411] opened 2018-06-05 10:08 UTC
Usually, my directories are sorted by name or extension, but my downloads directory I prefer to have sorted by file time, so the new items occur at the top of the list.

**Comment by mherrmann** [comment] 2018-06-05 11:31
fman does this when you sort using the keyboard (<kbd>Ctrl+F3</kbd>). It doesn't work when you sort with the mouse. I'll close this issue as a duplicate of #301.

**Closed as completed by mherrmann** 2018-06-05 11:31 UTC

**Comment by tmssngr** [comment] 2018-06-05 16:07
Does fman really remember different sorting modes for different directories?

**Comment by mherrmann** [comment] 2018-06-05 16:13
As I said - when you change the sort order via the keyboard (<kbd>Ctrl+F1/F2/F3</kbd>) then yes. It should remember it.

**Comment by tmssngr** [comment] 2018-06-05 17:11
So using the mouse is only temporarily where as using the keyboard is permanently? Is this by design or a bug?

**Comment by mherrmann** [comment] 2018-06-05 17:13
Yes. It's a bug.
