### ISSUE TITLE
Column sorting should be saved and recovered after reopening the program

### ISSUE THREAD

**Issue by ThePlagueD0ctor** [fman-community/fman#301] opened 2018-01-31 12:53 UTC
Steps to reproduce - 
change sorting direction or sorting column.
close fman.
Open fman
Expected: previous sorting is still applied
Actual: default sorting is applied

**Comment by mherrmann** [comment] 2018-02-01 12:42
Sorry for the trouble. I cannot reproduce this. Is this for a specific directory, or for all directories? Does the problem persist when you restart your computer?

**Comment by ThePlagueD0ctor** [comment] 2018-02-01 15:07
Hi! Computer restarting and folders have no influence on the problem. Just every time i launch fman it has default sorting (by name column).
I have Win10

**Comment by mherrmann** [comment] 2018-02-01 15:11
Thanks. And which folder are you viewing? Are you on the latest version of fman (0.8.7)? You can check by running the `About` command via the [Command Palette](https://fman.io/docs/shortcuts).

**Comment by ThePlagueD0ctor** [comment] 2018-02-01 15:31
Yeah, I have the latest version (0.8.7). 
Folders:
left - C:\<NameOfProject>
right - D:\Backups
So both are just random folders with a few files. 
Well, i even changed panes to just show C and D drives - the result is the same.
Also i noticed if a folder has a lot of files so a pane has a scrollbar - sort direction symbol (triangle) won't be shown in the last column (my case it's Modified column). It's hidden behind the scrollbar.

**Comment by mherrmann** [comment] 2018-02-05 18:20
Okay, thanks. You should have a file `C:\Users\<YOUR USER NAME>\AppData\Roaming\fman\Plugins\User\Settings\Sort Settings (Windows).json`. What are its contents?

**Comment by mherrmann** [comment] 2018-02-05 18:21
(P.S.: I released [fman 0.8.8](https://fman.io/changelog#v0.8.8) today. The sort triangle should no longer be hidden.)

**Comment by ThePlagueD0ctor** [comment] 2018-02-06 10:52
The "Settings" folder contains only 3 json files:
Panes (Windows)
Preview Settings (Windows)
Visited Paths (Windows)
Also the triangle is still hidden:
http://take.ms/laBeX3
http://take.ms/S53rm

I installed it a week ago or so from your site and didn't reconfigure anything manually)
Reinstalling of fman doesn't help

**Comment by mherrmann** [comment] 2018-02-07 07:51
I have an idea what might be causing this. @ThePlagueD0ctor, I assume you clicked on Modified column with the mouse to change the sort order. Are sort settings also not remembered when you press `Ctrl+F3` instead?

I created a new issue for the sort triangle: #307. Let's continue the discussion for this bug there please.

**Comment by ThePlagueD0ctor** [comment] 2018-02-07 11:33
Yea, previously i was clicking with the mouse on Modified column to change the sorting. Ctrl+F3 changes sort order of Modified column successfully, but if i reopen fman - both panes will be sorted by "name" column again.

Whatever sorting (and order) was before i closed the app - after launch it back i see following things:
1) The app loads with one column per pane (name) with sort order asc (triangle directs up)
2) Then Size and Modified columns are added to both panes. Sort keeps by "name" asc
3) Sort becomes by "name" desc (triangle directs down) and license pop-up appears

**Comment by mherrmann** [comment] 2018-02-07 11:40
Hm... Does the file `Sort Settings (Windows).json` exist now?

**Comment by mherrmann** [comment] 2018-02-07 11:42
(Here's why I'm asking: Clicking with the mouse changes the sort order "directly". When you press `Ctrl+F3` on the other hand, this invokes fman's command `SetSortOrder`. This saves to `Sort Settings.json` and _then_ changes the sort order directly. So my suspicion is that the file previously didn't exist because you used the mouse. Obviously, that would still make it a bug.)

**Comment by ThePlagueD0ctor** [comment] 2018-02-07 11:51
As I mentioned yesterday - there wasn't SortSettings.json file. And it is there.
So it really doesn't remember anything after mouse clicks. 
But after Ctrl+F3 it adds folder to the file with sorting info and after reopening of fman it keeps correct order but not "column " (it sorts by name but with correct sort direction)

**Comment by kamilakis** [comment] 2018-02-12 18:43
This is happening on Mac as well. Running latest version 0.8.9. It helps if the file manager 'remembers' sort settings per directory. I have tried editing the SortSettings.json file by hand, specifically I tried setting the "column" to "Modified" but it didn't work and it's contents are rewritten automatically to this:
`{"file:///Users/user/invoices": {"is_ascending": true, "column": "fman.impl.plugins.plugin.ColumnWrapper"}}`

**Comment by mherrmann** [comment] 2018-02-14 14:08
Those are interesting findings @kamhlos, thanks. I believe the problem is the `fman.impl.plugins.plugin.ColumnWrapper` (it should be `core.Name` or similar instead). I'm in the middle of some backend development work for fman and will get back to this after.

**Comment by aksh1618** [comment] 2018-06-29 23:11
Just to add a bit, I'm also facing this on Arch linux, v1.1.1.

**Comment by mherrmann** [comment] 2018-08-02 06:40
I fixed this now, as follows: Previously, fman only remembered the sort order when you changed it via the keyboard (<kbd>Ctrl</kbd>+<kbd>F1/F2/F3</kbd>). So, it did not remember the sort order when you changed it by mouse. Now, fman saves the previous sort order on every directory change - independently of whether it was set by mouse. The fix will go live with fman 1.1.6.

**Comment by mherrmann** [comment] 2018-08-06 15:22
Fixed in [fman 1.1.6](https://fman.io/changelog#v1.1.6).

**Closed as completed by mherrmann** 2018-08-06 15:22 UTC
Labels: bug, 5 votes
