### ISSUE TITLE
Calculate folder(s) size

### ISSUE THREAD

**Issue by Raikiri** [fman-community/fman#660] opened 2019-06-02 06:16 UTC
Probably the main thing that fman lacks that make it impossible for me to use it as my go-to file manager is inability to calculate folder size by selecting it with space and also inability to calculate all subfolder sizes by ctrl+shift+enter.

I really like the premise of this project and hope it continues to be developed.

**Comment by mherrmann** [comment] 2019-06-03 12:44
Hi, thank you and I'm happy to hear you like fman's premise. I'm closing this issue as a duplicate of #47.

**Closed as completed by mherrmann** 2019-06-03 12:44 UTC
