### ISSUE TITLE
Offline installer not working

### ISSUE THREAD

**Issue by kalons7** [fman-community/fman#530] opened 2018-10-01 20:54 UTC
I downloaded the offline installer on 2 different Windows 10 PCs, and it does nothing when running.

**Comment by mherrmann** [comment] 2018-10-02 13:24
Interesting, thank you for letting me know. I can reproduce this on Win 10, but not on Win 7.

**Comment by mherrmann** [comment] 2018-10-02 13:42
The trick seems to be that you must run the offline installer as Admin

**Comment by mherrmann** [comment] 2018-10-02 14:46
Fixed. Will go live with fman 1.3.3.

**Comment by mherrmann** [comment] 2018-10-04 15:51
Fixed in [fman 1.3.3](https://fman.io/changelog#v1.3.3).

**Closed as completed by mherrmann** 2018-10-04 15:51 UTC
Labels: bug, windows

**Comment by kalons7** [comment] 2018-10-04 16:10
When I download and run the offline installer from http://download.fman.io/1.3.3/fmanSetup.exe, it just runs another instance fman but doesn't update the installed version.  I had to run the online installer.

**Comment by kalons7** [comment] 2018-10-04 16:16
Well, maybe not.  I think the issue is that I pinned fman to the Windows taskbar previously, and that shortcut is still launching the previous version.  I had to unpin, then run fman from its new location, then pin to the taskbar again.  I wonder if there is a way to pin in such a way that it always runs the latest.

**Comment by kalons7** [comment] 2018-10-04 17:34
Looks like I can pin the fman.exe in the top-level install folder instead of the running instance.

**Comment by kalons7** [comment] 2018-10-04 19:48
Actually, that doesn't work so well, because then pressing Win+<num> for that taskbar item opens a new instance of fman every time.

**Comment by mherrmann** [comment] 2018-10-05 06:50
Yeah, I can see that's a hassle. It's already discussed in #121. Maybe you can find further info there.

**Comment by mherrmann** [comment] 2018-10-05 06:51
Also related to Single Instance Mode (#81).
