### ISSUE TITLE
Open with editor doesn't work

### ISSUE THREAD

**Issue by greenelephant** [fman-community/fman#264] opened 2017-12-10 10:01 UTC
Nothing happens when I use "Open with editor" option from menu. When I create a file editor opens fine and I can save one. 

"Open with editor" doesn't work no matter if I use from command palette or shortcuts.

System: Arch Linux
Version 0.7.6-1

**Comment by mherrmann** [comment] 2017-12-10 10:18
That's strange. By "when I create a file" you mean `Shift+F4`?

**Comment by greenelephant** [comment] 2017-12-10 10:21
Yes, I can use Shift+F4 and it works just fine. File is created and then editor opens.

**Comment by mherrmann** [comment] 2017-12-10 10:24
Thanks for clarifying. And it also doesn't work when you then `F4` on the file that was just created?

**Comment by greenelephant** [comment] 2017-12-10 10:29
Exactly.

**Comment by mherrmann** [comment] 2017-12-10 10:30
Strange. Okay! Thanks. I'll take a look.

**Comment by greenelephant** [comment] 2018-01-11 11:01
Did you have a chance to look at this issue?
How do you open a file? (I'm a python programmer, maybe I could help). 
I would like to start using fman but it's useless without open in editor option.

**Comment by raguay** [comment] 2018-01-11 12:40
Do you have my version of OpenWithEditor that makes use of the BitBar editor selector? That plugin takes some extra configurations. If not set, it will look like nothing happens. I never got around to making it more friendly, but I will. As far as I know, I'm about the only one using it. It would be nice to get some stats on a plugins usages (hint, hint...). 😄

**Comment by mherrmann** [comment] 2018-01-11 12:46
:smile: subtle @raguay, veeery subtle ;)

@greenelephant I'll take another look today, sorry.

**Comment by mherrmann** [comment] 2018-01-11 15:38
But what @raguay said is actually an interesting question @greenelephant: Did you install any plugins?

**Comment by greenelephant** [comment] 2018-01-11 16:25
Guys, I removed user folder and started configuration from scratch. Everything is working fine. Now I have only ArrowNavigation plugin. Before this I had OpenWithEditor but haven't installed it now. Thank you for help :)

**Comment by mherrmann** [comment] 2018-01-11 16:29
Great to hear it's resolved! So it appears this was caused by a plugin overwriting an existing command. I didn't think people would overwrite commands, but some plugins did (why wouldn't they). That's why it's now officially [discouraged](https://fman.io/docs/api#DirectoryPaneListener.on_command) by the API.

Closing this issue :)

**Closed as completed by mherrmann** 2018-01-11 16:29 UTC
Labels: bug

**Comment by raguay** [comment] 2018-01-12 05:04
Sorry, but the latest version doesn't overwrite the command, but the keyboard assignment is redone using the new `bb open with editor` command.

**Comment by mherrmann** [comment] 2018-01-12 06:12
Yes, absolutely. What I meant was that an _old_ plugin overwrote the command, sorry. I was trying to highlight this an example of why it is better not to overwrite existing commands for (perhaps) other readers.
