### ISSUE TITLE
Trying to copy a filename when editing it results in copying the file itself (not the file name)

### ISSUE THREAD

**Issue by jbonney** [fman-community/fman#282] opened 2018-01-01 14:51 UTC
If I am in the right panel and try to edit a file name (Shift+F6) and then want to copy the name of the file (Ctrl+C), the file that was previously selected in the left panel is getting copied instead. It is therefore not possible to copy the file name.

OS: Linux Elementary Loki (based on Ubuntu 16.04.3)
fman version: 0.8.1

**Comment by mherrmann** [comment] 2018-01-02 15:10
Hi Jimmy,

I'm sorry but I cannot reproduce this (on my Ubuntu 16.04). What I did precisely was:

1. Start fman.
2. Press Tab to focus the right pane.
3. Press `Shift+F6` to edit the name of the current file under the cursor. This selects at least part of the file name.
4. Press `Ctrl+C`.
5. Open a text editor and paste into it with `Ctrl+V`.

As I would have expected, the name of the file in the right pane appeared in the text editor.

Are the steps you took similar? Does the problem appear every time? Even after an OS restart?

**Comment by jbonney** [comment] 2018-01-02 20:48
Hi Michael,

I think I found the culprit! This was the settings from the OS to reveal the mouse when clicking on the Ctrl key (see screenshot below). When de-activating this setting, then this is working as expected. Sorry for the confusion.

![screenshot from 2018-01-02 21 43 42](https://user-images.githubusercontent.com/1498014/34499419-4a17ee20-f006-11e7-82d7-b917a0d7a629.png)

I am not sure whether the issue shall be closed or not (considering that Ctrl+C works as expected in Sublime Text for instance). I let you decide how you want to handle it.

Jimmy

**Comment by mherrmann** [comment] 2018-01-03 14:38
Hey Jimmy,

thank you for letting me know. If it works in ST but not fman, then there is probably something that could be done to fix it. However, it's (I think) a pretty special use case and there are many other more important issues. I will close this as "wontfix" for now. It's still here for others to find if they encounter the same issue.

Cheers,
Michael

**Closed as completed** 2018-01-04 06:49 UTC
Labels: bug, linux
