### ISSUE TITLE
Delete doesn't work in v0.3.7

### ISSUE THREAD

**Issue by raguay** [fman-community/fman#127] opened 2017-03-29 04:50 UTC
The delete functionality just quite working. Not sure why. Removing all extensions and it still quite working. Weird.

**Comment by mherrmann** [comment] 2017-03-29 04:55
You mean it's not possible to delete files?

**Comment by raguay** [comment] 2017-03-29 04:59
Yep. Whether by hotkey or command pallete. The move to trash functionality is dead on the Mac. I guess I hadn't needed to delete for the last few days. But, now I do.

**Comment by mherrmann** [comment] 2017-03-29 05:16
Does anything happen when you delete? Eg. do you get an error? Does the problem persist across (OS) restarts?

**Comment by raguay** [comment] 2017-03-29 05:45
It still gives the dialogue asking if I want to delete the file(s) or not. Other than that, nothing happens. I've rebooted, and running fman without extensions and it still doesn't delete. The earlier version did. It's working fine on my Linux system.

**Comment by mherrmann** [comment] 2017-03-29 05:49
I just tested with v0.3.7 on my machine and cannot reproduce the issue. Does it happen with all files? What if you create a file via `Shift+F4`, then delete it again?

**Comment by raguay** [comment] 2017-03-29 05:51
Any file or directory will not delete for me right now. I created test.txt with the Shift+F4 and then tried to delete it. It still is there.

**Comment by raguay** [comment] 2017-03-29 05:57
My OS version is 10.12.4 (16E195). I just updated to it and then notice the problem. I'm not sure if the problem existed before the update or not.

**Comment by mherrmann** [comment] 2017-03-29 05:57
Interesting. I'll try to update as well and see if I can reproduce then.

**Comment by macosxguru** [comment] 2017-03-29 06:01
Something in Richard's system. I am using the latest version of the OS and obviously on a Mac. Delete works fine here.

macosxguru

**Comment by raguay** [comment] 2017-03-29 06:34
Okay. I finally got my other Mac to install the latest version of fman and it deletes fine there. How could it not work on this system? Unless, something was left over from the dev version you had me try out.

**Comment by raguay** [comment] 2017-03-29 06:45
I deleted fman.app and re- installed. It still will not delete.

**Comment by raguay** [comment] 2017-03-29 06:50
Okay, I've removed fman completely from my system and re- installed. The totally unregistered, no extensions, nothing added to it version still will not delete a file or a directory! Very weird. Works fine on my Mac Mini with the exact same OS versions. Also, works fine on Linux. It's just my MacAir.

**Comment by mherrmann** [comment] 2017-03-29 07:23
I also can't reproduce on macOS 10.12.4.

fman's implementation for putting files to the Trash on Mac uses [this library](https://github.com/mherrmann/osxtrash) which in turn is based on [this one](https://github.com/ali-rantakari/trash). I'd like to find out whether the problem is caused by the library, or by the step where fman calls the library.

Could you please execute the following commands in a terminal?

```
git clone https://github.com/ali-rantakari/trash
cd trash
git checkout d7bac872cffafcc7e3806db292a4a2f250fbce2a
make
# Now use the `trash` command to move a file to the Trash:
./trash [path to some file]
```

You'll please have to replace `[path to some file]` by an actual file.

After the above steps, the file you chose should have been put to the Trash.

**Comment by raguay** [comment] 2017-03-29 07:28
I can't check out that branch because I'm in a "Detached HEAD" state. I've never figure out that issue with a git repository.

**Comment by mherrmann** [comment] 2017-03-29 07:29
That shouldn't be a problem. You should still be able to call `make` and then `./trash ...`. Or aren't you?

**Comment by mherrmann** [comment] 2017-03-29 07:31
"Detached HEAD" basically means that you are not on a branch, but at an individual commit. When you're on a branch and perform a commit, the branch is updated to point to the new commit. In "detached HEAD", this is not possible (because you're not on a branch).

**Comment by raguay** [comment] 2017-03-29 07:31
I'm trying that out now. I just got the upgraded Xcode and it's not set up right for command tools. I have to run it first and set the directories.

**Comment by mherrmann** [comment] 2017-03-29 07:39
I'm attaching my version so you don't have to waste time setting up Xcode.
[trash.zip](https://github.com/fman-users/fman/files/878171/trash.zip)

**Comment by raguay** [comment] 2017-03-29 07:52
Both the copy you sent and the one I downloaded from GitHub work fine. I believe that is the same library I used in an Alfred workflow.

**Comment by raguay** [comment] 2017-03-29 07:57
Guess what. Now that Xcode is running again (command line tools), fman is now deleting again! Could there be a library or something that is needed to work or am I just going crazy!

**Comment by mherrmann** [comment] 2017-03-29 08:01
I'm sure you're not going crazy. That's really strange. I wish we could "break" Xcode again to see what the root cause is/was. But if the problem has gone away now, I would close this issue and re-open it in case it occurs again. Do you agree?

**Comment by raguay** [comment] 2017-03-29 08:23
sounds good.

**Comment by raguay** [comment] 2017-07-28 02:03
Hi,

5.7 is having problems deleting again. Some things delete, some things don't. More items don't delete than do delete. Nothing is showing in the console. Not sure how to debug this issue. Any ideas?

**Comment by mherrmann** [comment] 2017-07-28 04:08
Did it work in 0.5.6? I'm reopening this issue. Are you on a development version of macOS? 0.5.7 didn't see any changes related to deleting files, so I don't think it's this particular version that could be the cause of the problem.

**Comment by raguay** [comment] 2017-07-28 15:53
macOS   10.12.6 (16G29)

I've heard that this version has some changes in the default python, but I use python installed from Homebrew ( Python 2.7.10 and Python 3.6.2 ). The problem isn't all the time as it was before, but only sometimes. I haven't been able to figure out what causes it (file location, file type, etc). Every time it does happen, the path does contain unusual characters (spaces, colons, etc). But some files with those items do delete. Weird.

**Comment by mherrmann** [comment] 2017-07-28 15:54
Is it reproducible when you keep the file name the same?

**Comment by raguay** [comment] 2017-07-31 12:35
Sorry. I'm traveling a lot lately and don't get my messages regularly.

I'm not sure what you mean by the question. When I can't delete, I simply drag it to the trashcan. Usable, but inconvenient and slows down my workflow. I haven't tried to edit the name and see if it will delete. Since it doesn't happen all the time now, it is a little harder to debug.

**Comment by mherrmann** [comment] 2017-08-23 06:03
What I meant by my question was: If you try again to delete the same file, does it still not work? Or does it work sometimes?

**Comment by raguay** [comment] 2017-09-29 15:28
I just figured out the issue. I use a macro to completely close out Finder since I use other file managers. When I close out Finder completely, that is when fman can't delete the files. As long as I have Finder running, fman deletes fine!

Therefore, maybe detect for Finder running and delete using low level delete when Finder isn't running. Doing it this way breaks the ability to put it back out of trash, but that isn't important to me.

**Comment by mherrmann** [comment] 2017-10-03 15:43
That's very interesting. I'm glad you were able to find the root cause.

How do you "close out" Finder? Do you still get a process ID when you type

    pgrep Finder

into a Terminal? I'm asking to find out how fman could determine whether Finder is closed out or not. I just tried and I am unable to close out Finder completely (it immediately respawns).

**Comment by raguay** [comment] 2017-10-03 19:45
I use a Keyboard Maestro macro to close fman. It simply is a quite finder macro and it works quite well. 

pgrep Finder finds other programs with "Finder" in their name. Ie: 'Path Finder', etc. You should be able to create a script to look for Finder.app. I've used:

ps -aux | grep '\/Finder.app'

Which seems to work.

**Comment by raguay** [comment] 2017-10-03 21:34
This AppleScript works as well:

on is_running(appName)
	tell application "System Events" to (name of processes) contains appName
end is_running

set finderRunning to is_running("Finder")
if finderRunning then
	return "Running"
else
	return "Not running"
end if

I imagine the same can be done in Swift for speed.

**Comment by raguay** [comment] 2017-10-04 01:54
I emailed you a Swift program for detecting if Finder is running or not. Maybe you can use it.

**Comment by raguay** [comment] 2017-10-05 15:28
I created a MoveToTrash replacement plugin to fix the issue for myself. It is here:  https://github.com/raguay/FlexibleTrash

**Comment by mherrmann** [comment] 2017-10-05 16:58
Thank you for sharing your solution. I'm working on the new FS implementation and haven't had much time to check my email much in the past few days. It's great that the plugin is there now. Since (I believe) Finder not running is quite exceptional, I will leave it at that for now and close this issue. If other people encounter the issue in the future as well, we can think about integrating a solution along the lines of yours into the Core plugin to begin with.

**Closed as completed by mherrmann** 2017-10-05 16:58 UTC
Labels: bug, mac, 1 vote

**Comment by xube** [comment] 2023-01-12 10:39
I have very similiar problem. When i press cmd+backspace or f8 the result is same. It prompts me about deleting and deletes files. After second files/folders are back. Same result with refreshing after removing. Copy (F5) or Move (F6) command is working. So file permission is not the problem.
