### ISSUE TITLE
Severe rename bug deletes folders

### ISSUE THREAD

**Issue by zelk** [fman-community/fman#357] opened 2018-04-13 06:06 UTC
Create a folder called "a". Rename it to "A". Notice how the folder and all its contents is deleted from the disk without warning. Only tested on Mac.

I just wiped an entire folder with lot's of data in it. I wanted to rename a folder called "agreements" to "Agreements". Luckily, I will be able to reproduce the information but others might not be so lucky.

**Comment by mherrmann** [comment] 2018-04-13 06:08
Sheesh I'm sorry. I will look at this straight away.

**Comment by raguay** [comment] 2018-04-13 06:15
I've tried several variations and I can't reproduce it. Does it happen all
the time? I'm on a mac as well with the latest OS and fman 0.9.9.

Also, the information should of been placed into the Trash unless you have
finder turned off and my Flexible trash installed. Then it will be deleted
permanently.

Richard

**Comment by mherrmann** [comment] 2018-04-13 06:47
I also cannot reproduce this. I create a folder "a" with a file "file.txt" in it. I then used <kbd>Shift+F6</kbd> to rename the folder to "A". The folder was renamed and the file then existed at "A/file.txt", as expected. Any further light you could shed on this would be highly appreciated @zelk.

**Comment by zelk** [comment] 2018-04-13 17:06
I can try again tomorrow. I used F6, not Shift-F6.

**Comment by raguay** [comment] 2018-04-14 04:08
F6 should of moved the folder to the directory in the other panel. Check the directory the other panel was in and your files should be there.

**Comment by zelk** [comment] 2018-04-15 19:27
Yes, I know what F6 is supposed to do but I tend to use it also to rename things in the same folder (as I was not aware of Shift+F6). So, please try to reproduce the bug by renaming a folder using F6 instead of Shift+F6 and see if you can reproduce it. On my computer, there's a 100 % repro rate.

**Comment by zelk** [comment] 2018-04-15 19:28
So, to be clear, position the cursor on a folder called "a", hit F6, remove everything in the textbox and only write "A". Notice that fman deletes the folder.

**Comment by mherrmann** [comment] 2018-04-16 09:09
You are right. I'm so sorry for this. I just fixed it. Will go live with upcoming fman 1.0.

**Comment by zelk** [comment] 2018-04-17 10:47
Great work! :)

**Comment by mherrmann** [comment] 2018-04-19 10:01
Fix released as part of [fman 1.0.0](https://fman.io/changelog#v1.0.0) :)

**Closed as completed** 2018-04-19 10:01 UTC
Labels: bug, mac
