### ISSUE TITLE
Allow 'get_info' to use Path Finder instead of Finder

### ISSUE THREAD

**Issue by eugenesvk** [fman-community/fman#207] opened 2017-08-13 12:38 UTC
I've noticed that the `get_info` command always uses **Finder**, despite the fact that I've defined **Path Finder** as the `native_file_manager` and also set it as the default file manager for `reveal` commands and such.
Would you please change that behavior? I didn't get rid of that Finder process just to have it stare at me every time I want to see some folder info :)
(I'm using a **ShowFileProperties** in the meantime, but it's not (nor, I guess, should it be) as complete)

**Comment by mherrmann** [comment] 2017-08-14 05:15
Hi Evgeny,

"Get Info" is a very Finder-specific command. It's therefore not easy to replicate its behavior with other file managers (such as Path Finder). Basically, what is required is an interface / command line option offered by Path Finder for launching _its_ Get Info dialog. I don't know if that exists. If it does, it won't be hard to write a little fman plugin to do what you want.

I suggest you find out if Path Finder's "Get Info" dialog can be launched from a terminal / via AppleScript. If yes, I can help you write the fman plugin. Just reply here. I'm closing this issue for now because this is currently outside the scope of "core" fman. You should still be able to reply if the issue is closed. If not, ping me at [my first] @ [my last] dot io. (Michael Herrmann - double r, double n).

Cheers

**Closed as completed by mherrmann** 2017-08-14 05:15 UTC
Labels: enhancement, mac

**Comment by eugenesvk** [comment] 2017-08-14 20:44
Ok, understood. Unfortunately, Path Finder is pretty awful in exposing its functionality to Applescript (and a bit of googling confirmed that ther is no script to launch a "Get Info" dialogue), so don't think this can be done in a similary way to Finder :(

**Comment by mherrmann** [comment] 2017-08-15 04:31
That's a pity :( Thank you for the research.
