### ISSUE TITLE
Styles overwritten with each update

### ISSUE THREAD

**Issue by blokeley** [fman-community/fman#506] opened 2018-09-06 10:47 UTC
I need to set some styles in `C:\Users\USERNAME\AppData\Local\fman\Versions\1.x.x\os_styles.qss`.

Specifically, I set the following:

```
Quicksearch QListView {
	min-width: 150ex;
	margin-left: .8ex;
	margin-right: .8ex;
}
```
to
```
Quicksearch QListView {
	min-width: 70em;
	margin-left: 1em;
	margin-right: 1em;
}
```

The problem is that the `os_styles.qss` file is replaced every time a new version is installed.

Can fman implement some kind of cascading style sheet [not a new idea!] whereby the default settings are loaded, then one or more user settings file which can update those default settings?

**Comment by mherrmann** [comment] 2018-09-06 10:53
fman already has [very basic Theme support](https://fman.io/docs/font-size-and-family). Full theme support is #45. 

But I'm wondering, why do you need those style sheet changes? Maybe I could integrate your changes into fman, so other people benefit from them as well?

**Comment by blokeley** [comment] 2018-09-06 12:11
Please do migrate those changes!

I needed a wider list widget so that I could read the length of my file names.  All the file names of interest to me start with `~\Dropbox (Company name)\Projects` and my company name is not short.

If my edit becomes the default we could close this issue in preference to #45

**Comment by mherrmann** [comment] 2018-09-07 12:30
I just tried with your settings on my machine, and it's unfortunately way too wide:

![image](https://user-images.githubusercontent.com/1076393/45219128-30efb380-b2aa-11e8-83af-0e125f892d5c.png)

Also the margins are way too wide.

Do you maybe have a screenshot of how this looks on your system?

Finally, maybe the solution to this problem will not be to make GoTo wider, but to make it more smartly display those parts of the file path that are relevant. Eg., it could cleverly hide the `~\Dropbox (Company name)\Projects` part from the paths.

**Comment by omisys** [comment] 2018-09-12 08:26
It would be nice to shorten the paths from dropbox indeed, that would be a good idea. Maybe the size of the bar could also fluctuate based on the longest path it found. Or it could just show the last part of the path instead of the first. For now I've also edited the qss to fit my path length.

**Comment by mherrmann** [comment] 2018-10-01 15:55
I've created a new issue (#527) for cleverly shortening the paths.

Closing this issue because the styles in fman's installation directory being overwritten is not a bug. As I mentioned above, full theme support (#45) will solve this problem.

**Closed as completed by mherrmann** 2018-10-01 15:55 UTC
Labels: discussion

**Comment by blokeley** [comment] 2018-10-25 08:51
I did another test and 50em width is fine for me.  Please change it from being measured in ex!
