### ISSUE TITLE
Drag & Drop: Used to move, now just copies. Make it configurable.

### ISSUE THREAD

**Issue by raguay** [fman-community/fman#322] opened 2018-02-16 02:18 UTC
Originally, dragging a file(s) onto a directory in the panel would move them to that directory. Now, it just copies them. Could you make this configurable so that each user could have it the way they like it? Add a command `dragdrop move` and `dragdrop copy`? Or, something like that.

**Comment by mherrmann** [comment] 2018-02-16 07:03
I would rather treat this as a bug? The normal behavior for file managers (eg Finder) is to move by default, and copy when you press (I believe) `Option` when dragging.

**Comment by raguay** [comment] 2018-02-16 07:26
Either way. I prefer the move option, but some people might like that it copies. I always have to look for the cursor change shape to know if it moves or copies.

**Comment by mherrmann** [comment] 2018-02-16 08:12
Okay, I'll treat it as a bug for now because it's the "standard" behavior for file managers. This way you also get what you want (move being the default).

**Comment by klutchnikoff** [comment] 2018-02-21 16:39
The same bug occurs using cut[Ctrl+X] / paste [Ctrl+V].

**Comment by mherrmann** [comment] 2018-02-21 16:40
That's Ubuntu 17.10 @klutchnikoff?

**Comment by klutchnikoff** [comment] 2018-02-21 17:40
Yes.

**Comment by mherrmann** [comment] 2018-02-23 16:30
I'm sorry @klutchnikoff I cannot reproduce this with `Ctrl+X`/`Ctrl+V` on Ubuntu 16.10. I tried the following combinations:

- fman -> fman
- fman -> Nautilus
- Nautilus -> fman

I tried each of these with both a single and with two files. In every case, the files were moved as expected (or fman opened the `Move...` dialog, which is also expected). What precisely were the steps you took that exhibit the issue?

**Comment by klutchnikoff** [comment] 2018-02-23 22:43
Hummm...

fman -> fman : the bug occurs (the `copy...` dialog appears)
Nautilus -> fman : same thing
fman -> Nautilus : nothing is happening (No copy, no move, nothing!)

However `Move [F6]` works as expected.

In fact I'm using the Wayland "flavor" of Ubuntu 17.10 (Gnome 3). I don't know if the problem is related to this. I'll perform some tests under xorg.

**Comment by mherrmann** [comment] 2018-02-26 11:40
@klutchnikoff, okay, would be great if you could let me know what you find. I've opened a [separate issue](https://github.com/fman-users/fman/issues/330) for this. If okay with you, I'd like to continue the discussion there please.

Regarding drag and drop, the bug has been there since at least version 0.5.8 on Linux.

**Comment by mherrmann** [comment] 2018-02-26 12:18
On Mac:
 * in 0.8.4 dragging from Finder into fman doesn't work at all. fman -> Finder does work
 * up to 0.7.1, fman <-> Finder both work as expected
 * in 0.7.2, 0.7.3, 0.7.5, 0.8.1, 0.9.0 Finder -> fman copies instead of move, fman -> Finder works as expected (moves)

So it seems the bug was introduced in 0.7.2.

**Comment by mherrmann** [comment] 2018-02-27 08:52
Fixed in [fman 0.9.1](https://fman.io/changelog#v0.9.1) :-)

**Closed as completed by mherrmann** 2018-02-27 08:52 UTC
Labels: bug
